# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
