# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
